sftp:
  dev:
    host: 'localhost'
    port: 22
    username: 'edge'
    password: 'edge@1234'
  uat:
    host: 'localhost'
    port: 22
    username: 'edge'
    password: 'password'
  pre:
    host: 'localhost'
    port: 22
    username: 'edge'
    password: 'password'
  remoteDir: '/home/dubbril/inbox/edw/archive/'
  localDir: 'C:\Users\dubbril\Desktop\localDir\'
  export: "/home/dubbril/edw/outbox/process/"

keysToMask:
  - key
  - data